services:

  db:
    build:
      context: database
    container_name: vdm_db
    volumes:
      - vdm_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .db.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -h db -p 5432 -d vdm_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
   image: node:24.8.0-alpine
   working_dir: /app
   container_name: vdm_frontend
   volumes:
     - ./frontend/vigie-du-mensonge:/app
     - /app/node_modules
   command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
   ports:
      - "5173:5173"

  openapi:
    build:
      context: openapi
    container_name: vdm_openapi
    restart: no
    volumes:
      - vdm_openapi_docs:/app/docs

  backend:
    build:
      context: backend
    container_name: vdm_backend
    volumes:
      - vdm_openapi_docs:/app/docs
    ports:
      - "8080:8080"
    env_file:
      - .backend.env
      - .db.env
    depends_on:
      db:
        condition: service_healthy

  data_import:
    build:
      context: data_import
    container_name: vdm_data_import
    restart: no
    env_file:
      - .db.env
    depends_on:
      db:
        condition: service_healthy

volumes:
  vdm_pg_data:
  vdm_openapi_docs: